# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/logstash/logstash:5.3.0

RUN logstash-plugin install logstash-filter-translate

ADD /config/logstash.yml /usr/share/logstash/config/logstash.yml
